#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

#
# Copyright (C) 2010 Rafael Fernández López <ereslibre@ereslibre.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# This script works when you have a layout of the style:
#
# project
#     |- workingCopy
#     |- featureX
#     |- bug1234
#     \- featureY
#
# The workflow is simple: always work on "workingCopy" folder.

require "uri"
require "fileutils"

if ARGV.size != 1
	puts "usage: #$0 branch"
	Process.exit
end

pwd = FileUtils.pwd
repo_b = URI.split((URI.join "file://#{pwd}", "#{ARGV[0]}").to_s)[5]

`hg update null`
FileUtils.rm ".hg" if File.exists? ".hg"
FileUtils.ln_s "#{repo_b}/.hg", "."
FileUtils.cd "#{repo_b}"
`hg update null`
FileUtils.cd pwd
`hg update`
