#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

##
## Copyright (C) 2010 Rafael Fernández López <ereslibre@ereslibre.es>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

$: << File.expand_path(File.dirname(__FILE__))

require "find"
require "colorize"
require "xmlsimple"
require "fileutils"
require "progressbar"

require "phpclass"

if ARGV.size != 2
  puts("usage: #$0 rootXSDdirectory destinationDirectory")
  puts
  puts("\trootXSDdirectory\tThe root directory that contains all XSD files")
  puts("\tdestinationDirectory\tThe destination directory where autogenerated files will be created")
  Process.exit
end

root = ARGV[0]
destination = ARGV[1]

root_dir = File.open(root, "r")
file_list = Array.new
Find.find(root_dir) do |path|
  file_list << path if path =~ /(.+).xml$/
end
root_dir.close

FileUtils.mkdir_p(destination)

progress = ProgressBar.new("Generating", file_list.count * 3)

file_contents = Array.new
for file in file_list
  file_contents << XmlSimple.xml_in(file, { "KeyAttr" => "name" })
  progress.inc
end

php_classes = Array.new
for contents in file_contents
  php_classes << PHPClass.new(destination, contents)
  progress.inc
end

for php_class in php_classes
  php_class.write_class(php_classes)
  progress.inc
end

puts
puts "***".light_green
puts "*** Successful generation".light_green
puts "***".light_green
puts "*** Destination: #{File.expand_path(destination)}".light_green
puts "***".light_green
